language: objective-c
osx_image: xcode8.3
before_install:
- sudo gem install fastlane
script:
- fastlane beta
env:
  global:
    secure: tQ6reentUh6lHG4hMZH/hBWezYLWsrI5773jz0UONyvgzX7hZ0fAZfJaNpbx0igDbyWJR7ySrco6/9qNp9Y4YPj6ihvrV+ZgINTfRiGYdBYg+QW6eCSalEMOAIQskPsOeBjwqtduTqtNB/Eiw2KPp4P2rWo6S4m452opcYYpLtRK5S6VLveaYDInZyLtLKE4gT0DlTJJ1wup2oUGDQW2kGKlXx3DMgNuWCnY+vLdnBUs5d6iqC1GK8SDdZ9EJtAZuUDV4x4k5bAJQD84khqmrf/PZvUv7K+K8l08FgOseRSVY6GPsDAB/7z1/bUeATUlDkv8a9ofgH4nHJwVuWoCX9+kzshiMcPfxyEMEL2Bn48vYhdY+tSJX6HxKz2vLaRnmzi7vSZ51mFSfh859opstvyusijseCd7ctANJk7k9lMeNRd5xjQZvyNf2pYAbfX71zlxcFP3F4tSiewMImgXVg9rbx185SAePkHxzmgsWGIfborq3xgutn1n1JptBQNmOuKZXN6HI/XuPC95yKN1sFrWRqA3HixBA18y0HDM1Bn+l8y/aJiQZhVmJ+P/hyhicpAv7PeCcdryj9EMkfIFKydLoJtPNvWLI1+fEeuYy/1yOt3n255HeGnV70thSQE+PHLBIp8wqtGn8XiK28NF4e+Eq95Bm99JZDL/RF5FPgQ=
